# Generated by Django 5.0.4 on 2024-05-29 16:54

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo_url', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo_url', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MusicCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo_url', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('phone', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=125)),
                ('verified', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=250)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('ratings', models.ManyToManyField(blank=True, default=None, to='be_streamvibe.rating')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='be_streamvibe.user')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('release_year', models.IntegerField()),
                ('release_date', models.DateField(default=None, null=True)),
                ('duration', models.TimeField()),
                ('movie', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video_movie')),
                ('trailer', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video_trailer')),
                ('trailer_thumbnail', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image_trailer')),
                ('upcoming_movie', models.DateField(blank=True, null=True)),
                ('actors', models.ManyToManyField(to='be_streamvibe.actor')),
                ('directors', models.ManyToManyField(to='be_streamvibe.director')),
                ('genres', models.ManyToManyField(to='be_streamvibe.genre')),
                ('languages', models.ManyToManyField(to='be_streamvibe.language')),
                ('music_creators', models.ManyToManyField(to='be_streamvibe.musiccreator')),
                ('ratings', models.ManyToManyField(blank=True, default=[], to='be_streamvibe.rating')),
                ('reviews', models.ManyToManyField(blank=True, default=[], to='be_streamvibe.review')),
            ],
        ),
        migrations.CreateModel(
            name='Support_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.IntegerField(default=0)),
                ('message', models.TextField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='be_streamvibe.user')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='be_streamvibe.user'),
        ),
    ]
